bitcoinNetwork: bsv

indexUnconfirmedTx: False

logLevel: Debug

logFileName: ./nexa.log

endPointListenPort: 9090

endPointListenIP: 127.0.0.1
 
maxTxProcThreadsSystem: 24

maxTxProcThreadsPerBlock: 8

maxBitcoinPeerCount: 16

unresponsivePeerConnTimeoutSecs: 60

acivatePeerDiscovery: True

staticPeerList: []

allegoryVendorSecretKey: 1435cf8e437d789eac332c3c66b2a51876e58c21db4b4da15488c3decb1a8b57

maxTMTBuilderThreads: 32

maxTMTQueueSize: 512
