resolver: lts-14.7
packages:
    - .
    - ../core
    - ../p2p


    extra-dep: true
extra-deps:
  - rocksdb-query-0.3.0
  # - git: https://github.com/bitemyapp/esqueleto.git
  # commit: 08c9b4cdf977d5bcd1baba046a007940c1940758
  # - git: https://github.com/stoichammer/arivi.git
  #   commit: db3217473a5cb5fcfa23960e749cd4d6eb72ee3d
  #   subdirs:
  #     - arivi-p2p
  # - github: snoyberg/conduit
  #   commit: 2e3e41de93821bcfe8ec6210aeca21be3f2087bf
  #   subdirs:
  #     - network-conduit-tls
